USE QuanLyDeAn2;

ALTER TABLE PHONGBAN ALTER COLUMN TenPhg nvarchar(30)

ALTER TABLE DEAN ALTER COLUMN DDiemDA nvarchar(20)

ALTER TABLE THANNHAN ALTER COLUMN TenTN nvarchar(20)

ALTER TABLE THANNHAN ALTER COLUMN Phai nvarchar(3)

ALTER TABLE THANNHAN ALTER COLUMN QuanHe nvarchar(15)

ALTER TABLE NHANVIEN ADD SoDienThoai varchar(15)

ALTER TABLE NHANVIEN DROP COLUMN SoDienThoai

